config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
# frozen_string_literal: true

class Item < ApplicationRecord
  validates :price, numericality: {greater_than: 0, allow_nil: true}
  validates :price, :description, presence: true

  after_initialize { p 'initialize' } # Item.new
  after_save { p 'save' } # Item.save
  after_create { p 'create' } # Item.create
  after_update { p 'update' } # Item.update
  after_destroy { p 'destroy' } # Item.destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
# frozen_string_literal: true

class ItemsController < ApplicationController
  layout false

  def index
    @items = Item.all
    render text: @items.map do |i|
      "#{i.name}:#{i.price}:#{i.description}"
    end
  end

  def create
    Item.create(items_params)
    render body: 'created'
  end

  def new

  end

  private

  def items_params
    params.permit(:name, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/index.html.erb
<% @items.each do |item| %>
  <ul>
    <li><%= item.name %> </li>
    <li><%= item.price %> </li>
    <li><%= item.description %> </li>
  </ul>
<% end %>

app/views/items/new.html.erb
<h2>Create new item</h2>
<%= form_tag new_item_path, method: :post do %>
  <%= label_tag :name %>
  <%= text_field_tag :name %>
  <%= label_tag :price %>
  <%= text_field_tag :price %>
  <%= submit_tag "Сохранить", class: "btn-btn-large btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsCourse</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= yield %>
</body>
</html>